version: 2.0

scenario_matrix:
  model_file: ['2Gt-UNC-2050','2Gt-UNC-2060','2Gt-E3']
  sector_model_file: []
  regions: [1-supply] #, 11-supply]
  resarea: [corridors]
  ll: [copt]
  opts: ['Co2L-1H']
  sector_opts: [2H]

logging:
  level: INFO
  format: "%(levelname)s:%(name)s:%(message)s"

# General inputs
data:
  resarea:
    redz: REDZ_DEA_Unpublished_Draft_2015
    corridors: Power_corridors
    #custom: allocation_study


# definition of the Coordinate Reference Systems
crs:
  geo_crs: EPSG:4326  # general geographic projection, not used for metric measures. "EPSG:4326" is the standard used by OSM and google maps
  distance_crs: EPSG:3857  # projection for distance measurements only. Possible recommended values are "EPSG:3857" (used by OSM and Google Maps)
  area_crs: ESRI:54009  # projection for area measurements only. Possible recommended values are Global Mollweide "ESRI:54009"

# When running the model for the first time it is necessary to enable the following scripts:
# build_natura_raster, build_population, build_topology, build_cutout. For subsequent model
# runs these scripts can be diabled to save time. Although snakemake will skip the execution
# of scripts where the outputs are already built, these switches are useful for forced 
# re-runs of the snakemake workflow, where you may not necessarily want to rebuild everything
enable:
  build_natura_raster: false # Rasters natural protection areas onto all cutout regions
  build_topology: true # Base network topology
  build_cutout: false #false # Atlite cutout 
  use_eskom_wind_solar: false # Model defaults to Eskom hourly pu profiles for all wind and solar generators
  use_excel_wind_solar: [false,"data/wind_solar_profiles.xlsx"] # Model defaults to excel input hourly pu profiles for all wind and solar generators  
  build_renewable_profiles: true #false # Enable calculation of renewable profiles

# Specification of relevent years for the model
years: 
  reference_demand_year: 2019  # should be a single year at present, could be extended in the future
  reference_weather_years: 
    # reference years used for solar PV and wind profiles - can be single or multiple years
    # if multiple years are specified these are applied sequencially to the simulation years
    solar: [2021]
    onwind: [2021]
    # reference years from actual Eskom data published at https://www.eskom.co.za/dataportal/ 
    # can be single or multiple years if multiple years are specified these are applied 
    # sequencially to the simulation years
    CSP: [2019] 
    biomass: [2019]
    hydro: [2019]
    hydro-import: [2019]

electricity:
  demand_disaggregation: 'GVA2016' # used to split the demand across supply regions in absence of Eskom data 
  co2limit: 2.2e+9    # Cumulative CO2 emissions budget for all simulation years combined
  renewable_carriers: [solar, onwind, CSP, biomass, hydro, hydro-import] # defines renewable carriers
  generator_availability: # generator planned and unplanned outages are included based on Eskom data
    implement_availability: true
    reference_years: [2019] #if multiple years specified an average is used
    new_unit_ref: 
    # New generator availability is based on an existing Eskom generator
    # in the format [generator, ref year/s (avg), rescale e.g 10% higher]
      coal: ['Lethabo', [2017], 1]
      OCGT: ['Ankerlig', [2017], 1]
      CCGT: ['Ankerlig', [2017], 1]
      nuclear: ['Koeberg', [2017], 1.1]

  # Only for new generators, existing generators are specified in model_file
  min_stable_levels:
    coal: 0 
    OCGT: 0 
    CCGT: 0
    nuclear: 0
    biomass: 0

  min_capacity_factor: # Minimum annual capacity factor 
    CCGT: 0.3 
    nuclear: 0.5

  extendable_carriers:
    Renewables: ['onwind', solar]
    Generator: [CCGT, OCGT, coal, nuclear, hydro-import]
    StorageUnit: [battery, PHS] 

  buses:
    11-supply: 
      OCGT: [Gauteng, Western Cape, KwaZulu Natal, Eastern Cape] # Saldana Bay, Richards Bay, Coega
      CCGT: [Gauteng, Western Cape, KwaZulu Natal, Eastern Cape]
      coal: [Gauteng, Limpopo] # Johannesburg, Waterberg
      nuclear: [Eastern Cape, Western Cape] # Thyspunt, Koeberg
      imports: [Limpopo]         
    27-supply:
      OCGT: [Johannesburg, West Coast, Empangeni, Port Elizabeth] # Saldana Bay, Richards Bay, Coega
      CCGT: [Johannesburg, West Coast, Empangeni, Port Elizabeth]
      coal: [Johannesburg, Waterberg]
      nuclear: [Port Elizabeth, Peninsula] # Thyspunt, Koeberg
      imports: [Polokwane]
    30-supply:
      OCGT: [Witbank, West Coast, Empangeni, Port Elizabeth] # Saldana Bay, Richards Bay, Coega
      CCGT: [Witbank, West Coast, Empangeni, Port Elizabeth]
      coal: [Witbank, Lephalale]
      nuclear: [Port Elizabeth, Peninsula] # Thyspunt, Koeberg
      imports: [Polokwane]  

  reserve_margin:
    coal: 0.8
    OCGT: 1
    CCGT: 1
    diesel: 1
    gas: 1
    biomass: 1
    onwind: 0.1 #.i.e only 10% of installed wind capacity is counted towards reserve_margin
    PHS: 1
    battery: 0.5

  operating_reserves:
      spinning: ['battery','PHS']
      total: ['diesel','gas','OCGT','CCGT','battery','PHS'] 
  max_hours:
    battery: 3
    PHS: 20
    H2: 10

respotentials:
  # Gives us ball-park the available areas the IWES study reports
  landusetype_percent:
  # grid codes
    wind:
      - [[7, 8, 9, 41], 80]
      # - [[5, 6], 50]
      # - [[11, 12, 14, 15], 10]
    solar:
      - [[7, 8, 9, 41], 80]
      # - [[11, 12, 14, 15], 50]
      # - [[46, 47, 51, 56, 64, 68, 72], 10]

  capacity_per_sqm:
    onwind: 5   # half of 10 (IWES)
    solar: 16.5 # half of 33 (IWES)

atlite:
  cutout_snapshots:
    start: "2020-01-01"
    end: "2021-01-01"
    #closed: 'left' # end is not inclusive
  nprocesses: 10
  cutouts:
    RSA-2020_22-era5:
      module: era5 # in priority order
      x: [16, 35]
      y: [-35., -21]
      dx: 0.3
      dy: 0.3
      time: ['2020','2022']
    RSA-2017_2019-era5:
      module: era5 # in priority order
      x: [16, 35]
      y: [-35., -21]
      dx: 0.3
      dy: 0.3
      time: ['2017','2019']
    # RSA-2012-sarah:
    #  module: [sarah, era5] # in priority order
    #  x: [16, 35]
    #  y: [-35.,-21]
    #  dx: 0.2
    #  dy: 0.2
    #  time: ['2012', '2012']
    #  sarah_interpolate: false
    #  sarah_dir:
    #  features: [influx, temperature]
  apply_wind_correction: true

renewable:
  onwind:
    cutout: RSA-2020_22-era5
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_2020ATB_4MW
    capacity_per_sqkm: 3 # ScholzPhd Tab 4.3.1: 10MW/km^2 and assuming 30% fraction of the already restricted
    # area is available for installation of wind generators due to competing land use and likely public
    # acceptance issues.
    # correction_factor: 0.93
    salandcover:
      grid_codes: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32]
      distance: 1000
      distance_grid_codes: [1, 2, 3, 4, 5, 6]

    #corine:
      # Scholz, Y. (2012). Renewable energy based electricity supply at low costs:
      #  development of the REMix model and application for Europe. ( p.42 / p.28)
    #  grid_codes: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32]
    #  distance: 1000
    #  distance_grid_codes: [1, 2, 3, 4, 5, 6]
    natura: true
    excluder_resolution: 100
    potential: simple # or conservative
    clip_p_max_pu: 1.e-2

  solar:
    cutout: RSA-2020_22-era5
    resource:
      method: pv
      panel: CSi
      orientation: latitude_optimal
        #slope: 35.
        #azimuth: 0.
    capacity_per_sqkm: 1.7 # ScholzPhd Tab 4.3.1: 170 MW/km^2 and assuming 1% of the area can be used for solar PV panels
    # Correction factor determined by comparing uncorrected area-weighted full-load hours to those
    # published in Supplementary Data to
    # Pietzcker, Robert Carl, et al. "Using the sun to decarbonize the power
    # sector: The economic potential of photovoltaics and concentrating solar
    # power." Applied Energy 135 (2014): 704-720.
    # This correction factor of 0.854337 may be in order if using reanalysis data.
    # for discussion refer to https://github.com/PyPSA/pypsa-eur/pull/304
    # correction_factor: 0.854337
  #  corine: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 26, 31, 32]
    natura: true
    excluder_resolution: 100
    potential: simple # or conservative
    clip_p_max_pu: 1.e-2
    salandcover:
      grid_codes: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32]
      distance: 1000
      distance_grid_codes: [1, 2, 3, 4, 5, 6]
  # hydro:
  #   cutout: RSA-2013-era5
  #   carriers: [ror, PHS, hydro]
  #   PHS_max_hours: 6
  #   hydro_max_hours: "energy_capacity_totals_by_country" # one of energy_capacity_totals_by_country, estimate_by_large_installations or a float
  #   clip_min_inflow: 1.0

hydro_inflow:
  disable: false #true
  source: eskom #or calculate runoff using atlite
  countries: [ZA, MZ] # only applicable to atlite
  cutout: za-mz-2012 # only applicable to atlite

lines:
  threshold: 220 # only voltages >=220kV are considered in network capacity calculations
  v_nom: 400. #changed from 380kV from PyPSA-EUR to 400kV for South Africa
  type: 
    400: 'Al/St 240/40 4-bundle 380.0' # proxy line properties from pypsa defaults
  s_rating:  thermal # thermal, SIL, StClair
  thermal:
    220: 492  #(MW) 'Al/St 240/40 2-bundle 220.0' -> np.sqrt(3)*220*1.29
    275: 921  #(MW) 'Al/St 240/40 2-bundle 220.0' -> np.sqrt(3)*275*1.935
    400: 1788 #(MW) 'Al/St 240/40 4-bundle 380.0' -> np.sqrt(3)*400*2.58
    765: 5512 #(MW) 'Al/St 560/50 4-bundle 750.0' -> np.sqrt(3)*765*4.16
  SIL: # surge impedance loading
    220: 122  #(MW) 
    275: 245  #(MW) 
    400: 602  #(MW) 
    765: 2280 #(MW) 
  s_max_pu: 0.7 # n-1 approximation
  s_nom_max: .inf
  length_factor: 1.25
  dc_type: "DC_custom_linetype"
  status: ["existing"] # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity
  extend_topology: true # if true, lines between adjacent regions that do not exist are added for expansion

links:
  p_max_pu: 1.0
  p_nom_max: .inf
  under_construction: "zero" # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity
  length_factor: 1.25

costs:
  # costs come from data/technology_costs.xlsx
  discountrate: 0.082
  year: 2030
  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   Wind: Bla
  marginal_cost: #
    solar: 0.01
    onwind: 0.015
    #offwind: 0.015 
    #PV: 0.01
    #Wind: 0.015
  USD_to_ZAR: 18.24
  EUR_to_ZAR: 17.83

  load_shedding: 100000 #R100/kWh
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    fuel: 0
    investment: 0
    lifetime: 25
    "CO2 intensity": 0
    "discount rate": 0.082

  emission_prices: # only used with the option Ep (emission prices)
    # Externality costs from Integrated Energy Plan by the ZA DOE
    co2: 0.27e+3
    sox: 7.6e+3
    nox: 4.5e+3
    hg: 41484.e-6 # is also part of the excel sheet
    particulate: 11.3e+3

tsam_clustering:
  normed: true
  extremePeriodMethod: 'None'
  rescaleClusterPeriods: False
  hoursPerPeriod: 24
  clusterMethod: 'hierarchical'
  nprocesses: 15
  solver: 'cbc' #need to use open source solver here due to parallel processing of years

solving:
  tmpdir: ./mytemp #/share/data1/DevKopSys2/ljansen/pypsa-za2/mytemp
  options:
    clip_p_max_pu: 1.e-2
    load_shedding: true
    noisy_costs: true
    skip_iterations: true
    min_iterations: 1
    max_iterations: 10
    msq_threshold: 0.05 # mean squared error threshold for convergence of iterations
    formulation: kirchhoff
    warmstart: false
    # max_iterations: 1
    # nhours: 10
  solver:
    # name: xpress
    # lpflags: 4
    # crossover: 0
    # bargapstop: 1.e-5
    # barstart: -1 #use xpress warmstart
    # #baralg: 2 
    # #barstartweight: 1
    # # FeasibilityTol: 1.e-6
    # # LogToConsole: 0
    # # OutputFlag: 1
    name: gurobi
    threads: 8
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-7
    OptimalityTol: 1.e-6
    Seed: 123
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200 #5000
    BarHomogeneous: 1
    BarOrder: 0



plotting:
  map:
    figsize: [10, 10]
    boundaries: [14, 34, -35, -22] #[x1,x2,y1,y2]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 3.e+3 #1.e+3 # 1.e+3  #3.e+3

  costs_max: 1000

  vre_techs: ["onwind","solar", "hydro", "hydro-import"]
  conv_techs: ["OCGT", "CCGT", "nuclear", "coal"]
  storage_techs: ["hydro", "CAES", "battery", "PHS", "hydro+PHS"]
  store_techs: ["Li ion", "water tanks"]
  load_carriers: ["AC load", "heat load", "Li ion load"]
  AC_carriers: ["AC line", "AC transformer"]
  link_carriers: ["DC line", "Converter AC-DC"] 
  heat_links: ["heat pump", "resistive heater", "CHP heat", "CHP electric",
               "gas boiler", "central heat pump", "central resistive heater", "central CHP heat",
               "central CHP electric", "central gas boiler"]
  heat_generators: ["gas boiler", "central gas boiler", "solar thermal collector", "central solar thermal collector"]
  tech_colors:
    "onwind": "#005b7f"  #"#77D1E4" #005b7f
    "onshore wind": "#005b7f"  #"#77D1E4"
    "offwind": "#005b7f"  #"#77D1E4"
    "offwind-ac": "#005b7f"  #"#77D1E4"
    "offshore wind": "#005b7f"  #"#77D1E4"
    "offshore wind ac": "#005b7f"  #"#77D1E4"
    "offwind-dc": "#005b7f"  #"#77D1E4"
    "offshore wind dc": "#005b7f"  #"#77D1E4"
    "hydro": "#99dccd"  #"#004F95"
    "hydro-import": "#a6bbc8"  #"#004F95"
    "hydro+PHS": "#4cc2a6"  #"#004F95"
    "PHS": "#4cc2a6"  #"#004F95"
    "hydro reservoir": "#99dccd"  #"#004F95"
    "hydroelectricity": "#99dccd"  #"#004F95"
    "ror": "#4adbc8"
    "run of river": "#4adbc8"
    "solar": "#fdb913"
    "solar PV": "#fdb913"
    "CSP": "#ffdd8a"
    "biomass": "#b2d235"
    "solid biomass": "#06540d"
    "biogas": "#23932d"
    "waste": "#dde4a2"
    "geothermal": "#ba91b1"
    "OCGT": "#d3c7ae"
    "gas": "#d3c7ae"
    "natural gas": "#d3c7ae"
    "CCGT": "#a39372"
    "nuclear": "#bb0056"
    "coal": "#3C3C3C"
    "lignite": "#9e5a01"
    "diesel": "#262626"
    "H2": "#ea048a"
    "hydrogen storage": "#ea048a"
    "battery": "#f58220"
    "Electric load": "#f9d002"
    "electricity": "#f9d002"
    "lines": "#179c7d"
    "transmission lines": "#179c7d"
    "AC-AC": "#179c7d"
    "AC line": "#3C3C3C"
    "links": "#7c154d"
    "HVDC links": "#7c154d"
    "DC-DC": "#7c154d"
    "DC link": "#7c154d"
    "load_shedding": "#FF0000"
    "Load": "#FF0000"
  nice_names:
    OCGT: "OCGT" #"Open-Cycle Gas"
    CCGT: "CCGT" #"Combined-Cycle Gas"
    offwind-ac: "Offshore Wind (AC)"
    offwind-dc: "Offshore Wind (DC)"
    onwind: "Wind"
    solar: "PV"
    PHS: "Pumped Hydro Storage"
    hydro: "Hydro"
    hydro+PHS: "Hydro+PS"
    battery: "Battery"
    H2: "Hydrogen Storage"
    lines: "Transmission Lines"
    ror: "Run of River"
    coal: "Coal"
    nuclear: "Nuclear"
    biomass: "Biomass"