# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: pypsa-rsa-sec-test

channels:
- conda-forge
- bioconda
dependencies:
- python>3.9
- pip
- mamba

- pypsa>=0.33
- atlite>=0.2.9
- linopy

- dask
- xlrd=2.0.1
- openpyxl!=3.1.1
- snakemake-minimal<8.0
- ruamel.yaml<=0.17.26
- pytables
- lxml
- numpy
- pandas>=2.1
- geopandas<1.0
- xarray>=2023.11.0
- fiona!=1.8.22
- xarray
- rioxarray
- netcdf4
- networkx
- scipy
- shapely>=2
- pre-commit
- pyomo
- matplotlib<=3.5.2
- reverse-geocode
- proj
- pyproj

  # Keep in conda environment when calling ipython
- ipython
  # Jupyter notebook requirement
- ipykernel
- jupyterlab

  # GIS dependencies:
- cartopy
- descartes
- rasterio<1.4
- rioxarray

 # Plotting
- plotly
- python-kaleido
#- geoviews
#- hvplot
- graphviz
#- contextily

  # PyPSA-Eur-Sec Dependencies
- geopy
- tqdm
- pytz

# Default solver for tests (required for CI)
- glpk
#- ipopt<3.13.3
#- gurobi

- pip:
  - gurobipy
  - highspy!=1.8.0 # No conda channel for arm macos
  - tsam>=1.1.0
#  - git+https://github.com/davide-f/google-drive-downloader@master  # google drive with fix for virus scan
  - git+https://github.com/FRESNA/vresutils@master  # until new pip release > 0.3.1 (strictly)
